repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.0.0
    hooks:
      - id: prettier
        files: \.(yaml|md)$ # The filename extensions this formatter edits
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md] # preserve Markdown hard linebreaks
      - id: check-merge-conflict
